// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMRePSiKXgrmSP60bxZFE9rjBdPHIE7oY',
    appId: '1:748104904384:web:9db046e0b2b8d57d1dc725',
    messagingSenderId: '748104904384',
    projectId: 'taskflow-b9bcc',
    authDomain: 'taskflow-b9bcc.firebaseapp.com',
    storageBucket: 'taskflow-b9bcc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa_m_lpEJvSfLJZV2VWJYNZEZ0Dgd-3MQ',
    appId: '1:748104904384:android:493a096dafe415611dc725',
    messagingSenderId: '748104904384',
    projectId: 'taskflow-b9bcc',
    storageBucket: 'taskflow-b9bcc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo_lvJMl9tuA2Eo2Ne6_EmKJDvmXEY3rA',
    appId: '1:748104904384:ios:e716ca5b693c8ead1dc725',
    messagingSenderId: '748104904384',
    projectId: 'taskflow-b9bcc',
    storageBucket: 'taskflow-b9bcc.firebasestorage.app',
    iosBundleId: 'com.example.taskflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo_lvJMl9tuA2Eo2Ne6_EmKJDvmXEY3rA',
    appId: '1:748104904384:ios:e716ca5b693c8ead1dc725',
    messagingSenderId: '748104904384',
    projectId: 'taskflow-b9bcc',
    storageBucket: 'taskflow-b9bcc.firebasestorage.app',
    iosBundleId: 'com.example.taskflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMRePSiKXgrmSP60bxZFE9rjBdPHIE7oY',
    appId: '1:748104904384:web:7fbace6e4562b3881dc725',
    messagingSenderId: '748104904384',
    projectId: 'taskflow-b9bcc',
    authDomain: 'taskflow-b9bcc.firebaseapp.com',
    storageBucket: 'taskflow-b9bcc.firebasestorage.app',
  );
}
